#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <openssl/evp.h>
#include <openssl/err.h>
#include <openssl/provider.h>

void handleErrors() {
    ERR_print_errors_fp(stderr);
    abort();
}

int main() {
    EVP_PKEY_CTX *pctx = NULL;
    EVP_PKEY_CTX *ctx_enc = NULL;
    EVP_PKEY_CTX *ctx_dec = NULL;
    EVP_PKEY *pkey = NULL;
    size_t outlen, keylen;
    unsigned char *out = NULL;
    unsigned char *secret_gpu = NULL;
    unsigned char *secret_cpu = NULL;
    int ret = 1;

    printf("\n=== ML-KEM-768 GPU CORRECTNESS TEST ===\n");

    /* 1. Load Standard Providers */
    if (OSSL_PROVIDER_load(NULL, "default") == NULL) handleErrors();

    /* 2. Key Generation (CPU - Your Production Choice) */
    printf("[1] Generating Key Pair on CPU... ");
    pctx = EVP_PKEY_CTX_new_from_name(NULL, "ML-KEM-768", NULL);
    if (!pctx) handleErrors();
    if (EVP_PKEY_keygen_init(pctx) <= 0) handleErrors();
    if (EVP_PKEY_keygen(pctx, &pkey) <= 0) handleErrors();
    printf("SUCCESS\n");

    /* 3. Encapsulation (GPU - The Test Subject) */
    printf("[2] Encapsulating on GPU (Tesla T4)... ");
    
    // FORCE ENABLE THE GPU
    setenv("ENABLE_CUPQC", "1", 1); 

    ctx_enc = EVP_PKEY_CTX_new(pkey, NULL);
    if (!ctx_enc) handleErrors();
    
    // FIX: Added NULL as the second argument
    if (EVP_PKEY_encapsulate_init(ctx_enc, NULL) <= 0) handleErrors();

    // Determine Buffer Lengths
    if (EVP_PKEY_encapsulate(ctx_enc, NULL, &outlen, NULL, &keylen) <= 0) handleErrors();
    
    out = OPENSSL_malloc(outlen);        // Ciphertext
    secret_gpu = OPENSSL_malloc(keylen); // Shared Secret (from GPU)

    if (EVP_PKEY_encapsulate(ctx_enc, out, &outlen, secret_gpu, &keylen) <= 0) {
        printf("\n[ERROR] GPU Encapsulation Failed!\n");
        handleErrors();
    }
    printf("SUCCESS\n");
    printf("    -> Ciphertext generated by GPU.\n");
    printf("    -> Shared Secret generated by GPU.\n");

    /* 4. Decapsulation (CPU - The Verifier) */
    printf("[3] Decapsulating on CPU... ");

    // DISABLE GPU (Just to be safe, though Decap is CPU anyway)
    unsetenv("ENABLE_CUPQC");

    ctx_dec = EVP_PKEY_CTX_new(pkey, NULL);
    if (!ctx_dec) handleErrors();
    
    // FIX: Added NULL as the second argument
    if (EVP_PKEY_decapsulate_init(ctx_dec, NULL) <= 0) handleErrors();

    secret_cpu = OPENSSL_malloc(keylen); // Shared Secret (from CPU Decrypt)
    size_t secret_cpu_len = keylen;

    if (EVP_PKEY_decapsulate(ctx_dec, secret_cpu, &secret_cpu_len, out, outlen) <= 0) {
        printf("\n[ERROR] CPU could not Decapsulate!\n");
        handleErrors();
    }
    printf("SUCCESS\n");

    /* 5. Bit-Level Comparison */
    printf("[4] Verifying Bitwise Integrity... ");
    if (memcmp(secret_gpu, secret_cpu, keylen) == 0) {
        printf("\n\n[PASS] INTEGRITY CONFIRMED.\n");
        printf("The GPU (Encapsulator) and CPU (Decapsulator) agreed on the exact same secret.\n");
        printf("Mathematical correctness is verified.\n");
        ret = 0;
    } else {
        printf("\n\n[FAIL] DATA CORRUPTION DETECTED.\n");
        printf("The GPU produced a secret that the CPU could not derive.\n");
        ret = 1;
    }

    /* Cleanup */
    EVP_PKEY_CTX_free(pctx);
    EVP_PKEY_CTX_free(ctx_enc);
    EVP_PKEY_CTX_free(ctx_dec);
    EVP_PKEY_free(pkey);
    OPENSSL_free(out);
    OPENSSL_free(secret_gpu);
    OPENSSL_free(secret_cpu);

    return ret;
}
